// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: kiosks.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createKiosk = `-- name: CreateKiosk :one
INSERT INTO kiosks (
    id,
    ip,
    name
) VALUES (
    ?,
    ?,
    ?
) RETURNING id, ip, name
`

type CreateKioskParams struct {
	ID   uuid.UUID
	IP   string
	Name string
}

func (q *Queries) CreateKiosk(ctx context.Context, arg CreateKioskParams) (Kiosk, error) {
	row := q.db.QueryRowContext(ctx, createKiosk, arg.ID, arg.IP, arg.Name)
	var i Kiosk
	err := row.Scan(&i.ID, &i.IP, &i.Name)
	return i, err
}

const getKioskByID = `-- name: GetKioskByID :one
SELECT id, ip, name
FROM kiosks
WHERE id = ?
`

func (q *Queries) GetKioskByID(ctx context.Context, id uuid.UUID) (Kiosk, error) {
	row := q.db.QueryRowContext(ctx, getKioskByID, id)
	var i Kiosk
	err := row.Scan(&i.ID, &i.IP, &i.Name)
	return i, err
}

const getKioskByIP = `-- name: GetKioskByIP :one
SELECT id, ip, name
FROM kiosks
WHERE ip = ?
`

func (q *Queries) GetKioskByIP(ctx context.Context, ip string) (Kiosk, error) {
	row := q.db.QueryRowContext(ctx, getKioskByIP, ip)
	var i Kiosk
	err := row.Scan(&i.ID, &i.IP, &i.Name)
	return i, err
}
