// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: kiosks.sql

package database

import (
	"context"
	"strings"

	"github.com/google/uuid"
)

const createKiosk = `-- name: CreateKiosk :one
INSERT INTO kiosks (
    id,
    ip,
    name,
    name_key
) VALUES (
    ?,
    ?,
    ?,
    ?
)
RETURNING id, ip, name, name_key, version
`

type CreateKioskParams struct {
	ID      uuid.UUID
	IP      string
	Name    string
	NameKey string
}

func (q *Queries) CreateKiosk(ctx context.Context, arg CreateKioskParams) (Kiosk, error) {
	row := q.db.QueryRowContext(ctx, createKiosk,
		arg.ID,
		arg.IP,
		arg.Name,
		arg.NameKey,
	)
	var i Kiosk
	err := row.Scan(
		&i.ID,
		&i.IP,
		&i.Name,
		&i.NameKey,
		&i.Version,
	)
	return i, err
}

const getKioskByIP = `-- name: GetKioskByIP :one
SELECT
    id,
    ip,
    name,
    name_key,
    version
FROM kiosks
WHERE ip = ?
`

func (q *Queries) GetKioskByIP(ctx context.Context, ip string) (Kiosk, error) {
	row := q.db.QueryRowContext(ctx, getKioskByIP, ip)
	var i Kiosk
	err := row.Scan(
		&i.ID,
		&i.IP,
		&i.Name,
		&i.NameKey,
		&i.Version,
	)
	return i, err
}

const listKiosksByIDs = `-- name: ListKiosksByIDs :many
SELECT
    id,
    ip,
    name,
    name_key,
    version
FROM kiosks
WHERE id IN (/*SLICE:ids*/?)
ORDER BY name
`

func (q *Queries) ListKiosksByIDs(ctx context.Context, ids []uuid.UUID) ([]Kiosk, error) {
	query := listKiosksByIDs
	var queryParams []interface{}
	if len(ids) > 0 {
		for _, v := range ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Kiosk
	for rows.Next() {
		var i Kiosk
		if err := rows.Scan(
			&i.ID,
			&i.IP,
			&i.Name,
			&i.NameKey,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nameKeyHeldByOther = `-- name: NameKeyHeldByOther :one
SELECT EXISTS (
    SELECT 1
    FROM kiosks
    WHERE ip != ?1 AND name_key = ?2
) AS held
`

type NameKeyHeldByOtherParams struct {
	IP      string
	NameKey string
}

func (q *Queries) NameKeyHeldByOther(ctx context.Context, arg NameKeyHeldByOtherParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, nameKeyHeldByOther, arg.IP, arg.NameKey)
	var held bool
	err := row.Scan(&held)
	return held, err
}
