// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"github.com/google/uuid"
)

type Kiosk struct {
	ID   uuid.UUID
	IP   string
	Name string
}

type User struct {
	ID       string
	Username string
	Password string
}
