// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: refresh_tokens.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getRefreshToken = `-- name: GetRefreshToken :one
SELECT
    token,
    created_at,
    updated_at,
    user_id,
    expires_at,
    revoked_at
FROM refresh_tokens
WHERE token = ?
`

func (q *Queries) GetRefreshToken(ctx context.Context, token string) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, getRefreshToken, token)
	var i RefreshToken
	err := row.Scan(
		&i.Token,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const makeRefreshToken = `-- name: MakeRefreshToken :one
INSERT INTO refresh_tokens (
    token,
    created_at,
    updated_at,
    user_id,
    expires_at
) VALUES (
    hex(randomblob(32)),
    datetime('now'),
    datetime('now'),
    ?,
    ?
)
RETURNING token, created_at, updated_at, user_id, expires_at, revoked_at
`

type MakeRefreshTokenParams struct {
	UserID    uuid.UUID
	ExpiresAt time.Time
}

func (q *Queries) MakeRefreshToken(ctx context.Context, arg MakeRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, makeRefreshToken, arg.UserID, arg.ExpiresAt)
	var i RefreshToken
	err := row.Scan(
		&i.Token,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const revokeCurrentRefreshToken = `-- name: RevokeCurrentRefreshToken :one
UPDATE refresh_tokens
SET
    revoked_at = datetime('now'),
    updated_at = datetime('now')
WHERE token = ?
  AND revoked_at IS NULL
  AND expires_at > datetime('now')
RETURNING token, created_at, updated_at, user_id, expires_at, revoked_at
`

func (q *Queries) RevokeCurrentRefreshToken(ctx context.Context, token string) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, revokeCurrentRefreshToken, token)
	var i RefreshToken
	err := row.Scan(
		&i.Token,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const rotateRefreshToken = `-- name: RotateRefreshToken :one
UPDATE refresh_tokens
SET
    token = hex(randomblob(32)),
    created_at = datetime('now'),
    updated_at = datetime('now'),
    expires_at = ?
WHERE token = ?
  AND revoked_at IS NULL
  AND expires_at > datetime('now')
RETURNING token, created_at, updated_at, user_id, expires_at, revoked_at
`

type RotateRefreshTokenParams struct {
	ExpiresAt time.Time
	Token     string
}

func (q *Queries) RotateRefreshToken(ctx context.Context, arg RotateRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, rotateRefreshToken, arg.ExpiresAt, arg.Token)
	var i RefreshToken
	err := row.Scan(
		&i.Token,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}
