services:
  docu-kiosk:
    image: ghcr.io/gtkycu-it/docu-kiosk:latest
    env_file: .env
    restart: unless-stopped
    volumes:
      - app-data:/app/data
    networks:
      - caddy

volumes:
  app-data:

networks:
  caddy:
    external: true
